-- CreateTable
CREATE TABLE "payment_settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "paygateEnabled" BOOLEAN NOT NULL DEFAULT true,
    "paygateMerchantWallet" TEXT,
    "paygateBaseUrl" TEXT NOT NULL DEFAULT 'https://api.paygate.to',
    "paygateCheckoutUrl" TEXT NOT NULL DEFAULT 'https://checkout.paygate.to',
    "defaultProvider" TEXT NOT NULL DEFAULT 'MULTI_PROVIDER',
    "enabledProviders" TEXT NOT NULL DEFAULT 'moonpay,banxa,transak,stripe',
    "enableCreditCard" BOOLEAN NOT NULL DEFAULT true,
    "enableApplePay" BOOLEAN NOT NULL DEFAULT true,
    "enableGooglePay" BOOLEAN NOT NULL DEFAULT true,
    "enableBankTransfer" BOOLEAN NOT NULL DEFAULT true,
    "supportedCurrencies" TEXT NOT NULL DEFAULT 'USD,EUR,GBP,CAD',
    "defaultCurrency" TEXT NOT NULL DEFAULT 'USD',
    "platformFeePercentage" REAL NOT NULL DEFAULT 5.0,
    "paygateFeePercentage" REAL NOT NULL DEFAULT 1.0,
    "minimumOrderAmount" REAL NOT NULL DEFAULT 5.0,
    "maximumOrderAmount" REAL NOT NULL DEFAULT 10000.0,
    "escrowEnabled" BOOLEAN NOT NULL DEFAULT true,
    "escrowThreshold" REAL NOT NULL DEFAULT 100.0,
    "escrowAutoReleaseHours" INTEGER NOT NULL DEFAULT 72,
    "testMode" BOOLEAN NOT NULL DEFAULT false,
    "customDomain" TEXT,
    "callbackUrl" TEXT,
    "affiliateEnabled" BOOLEAN NOT NULL DEFAULT false,
    "affiliateWallet" TEXT,
    "affiliateFeePercentage" REAL NOT NULL DEFAULT 10.0,
    "updatedBy" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
